/* Author: Gilian Salo - ICT12 Lower Half - Group 1
 * This is our Java Project that is Titled A Day In a Life: DLSUD Edition
 * This program is a story simultion of different scenarios that a Lasallian student
 * may encounter during their time in DLSUD.
 * It aims to promote critical thinking and decision making as a Lasallian student.
 * We aim for this application to be used in grade 11 orientation to give them a 
 * vision or insight of what their Lasallian journey may be like.
 */
package javaproject1;

/*
 * @author Gilian
 */

// Make a public class that extends to JFrame, this will be the GUI.
public class LASALLIAN_SIM extends javax.swing.JFrame {

    /**
     * Creates new form LASALLIAN_SIM
     */
    public LASALLIAN_SIM() {
        initComponents();
        UserInput.setVisible(false);
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/1Character Choice.png")));
//        Input.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        BG = new javax.swing.JLabel();
        OPTIONA = new javax.swing.JButton();
        TEXT = new javax.swing.JLabel();
        UserInput = new javax.swing.JTextField();
        OPTIONB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaproject1/1Character  Choice.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), BG, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        OPTIONA.setText("MALE");
        OPTIONA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OPTIONAMousePressed(evt);
            }
        });
        OPTIONA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPTIONAActionPerformed(evt);
            }
        });

        TEXT.setText("Please Select your desired character");

        UserInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserInputActionPerformed(evt);
            }
        });

        OPTIONB.setText("FEMALE");
        OPTIONB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OPTIONBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OPTIONA)
                        .addGap(51, 51, 51)
                        .addComponent(OPTIONB))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TEXT)
                        .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(BG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TEXT)
                .addGap(45, 45, 45)
                .addComponent(UserInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OPTIONA)
                    .addComponent(OPTIONB))
                .addGap(358, 358, 358))
            .addComponent(BG)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OPTIONAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPTIONAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OPTIONAActionPerformed

    private void UserInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserInputActionPerformed

    private void OPTIONAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OPTIONAMousePressed
        Scenario = Scenario + 1;
        if(Scenario == 2) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/2BED TIME -M (2).png")));
            UserInput.setVisible(true);
            User = UserInput.getText();
            TEXT.setText(" you should go to bed its already 11pm you have a 7am class tomorrow!");
            OPTIONA.setText("Sleep");
            OPTIONB.setText("Keep Scrolling");
        } else if (Scenario == 3) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/3COR -M.png")));
            UserInput.setVisible(false);
            TEXT.setText(" Guard: do you have your COR?");
            OPTIONA.setText("Do not give COR");
            OPTIONB.setText("Present COR");
        } else if (Scenario == 4) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/3COR ENDING - M.png")));
            UserInput.setVisible(false);
            TEXT.setText("You have failed your Day as a Lasallian student and is not allowed to enter the campus due to not presenting your COR.");
            OPTIONA.setText("RESTART GAME");
            OPTIONB.setVisible(false);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_OPTIONAMousePressed

    private void OPTIONBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OPTIONBActionPerformed
   Scenario = Scenario + 1;
        if(Scenario == 2) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/2BED TIME -F.png")));
            UserInput.setVisible(true);
            User = UserInput.getText();
            TEXT.setText(" you should go to bed its already 11pm you have a 7am class tomorrow!");
            OPTIONA.setText("Sleep");
            OPTIONB.setText("Keep Scrolling");
        } else if (Scenario == 3) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/3COR -M.png")));
            UserInput.setVisible(false);
            TEXT.setText(" Guard: do you have your COR?");
            OPTIONA.setText("Do not give COR");
            OPTIONB.setText("Present COR");
        } else if (Scenario == 4) {
            BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LASALLIAN_SIM/3COR ENDING - M.png")));
            UserInput.setVisible(false);
            TEXT.setText("You have failed your Day as a Lasallian student and is not allowed to enter the campus due to not presenting your COR.");
            OPTIONA.setText("RESTART GAME");
            OPTIONB.setVisible(false);
        } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_OPTIONBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LASALLIAN_SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LASALLIAN_SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LASALLIAN_SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LASALLIAN_SIM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LASALLIAN_SIM().setVisible(true);
            }
        });
    }
    private String User = "";
    private int  Scenario = 1;
//    private String User = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JButton OPTIONA;
    private javax.swing.JButton OPTIONB;
    private javax.swing.JLabel TEXT;
    private javax.swing.JTextField UserInput;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
